# pyautocad

from pyautocad import Autocad, APoint

## 创建及保存

```
acad = Autocad(create_if_not_exists = True,visible=True)
acad.prompt("Connect Success") # 测试是否连接成功，成功则输出该行命令提示
print(acad.doc.Name,flush=True) # 输出创建的文件名(Drawing1.dwg)

acad.ActiveDocument.SaveAs(retpathName, 12)# 保存文件为retpathName.dwg
```

## 命令绘图

```
rStr = chr(13)

# 发送绘图命令
acad.ActiveDocument.SendCommand(cmdstr)

#直线
cmdstr = "L" + rStr + "0,0" + rStr + "100,100" + rStr + rStr
# 折线
cmdstr = "L" + rStr + "0,0" + rStr + "1000,1000" + rStr + "1200,1500" + rStr + rStr

# 矩形
cmdstr = "REC" + rStr + "100,200" + rStr + "1000,1500"  + rStr


```

## 绘图

```
p1 = APoint(0, 0)
p2 = APoint(50, 25)

# 文字
inf = "你好"
text = acad.model.AddText(inf, p1, 2.5)

# 直线
acad.model.AddLine(p1, p2)

# 圆，半径10
acad.model.AddCircle(p1, 10)

```

## cad系统设置

```
# 设置背景色
# R+256*G+256*256*B; 0:黑色 255:红 65535:黄 65280:绿 16776960:青 16711680:蓝色 16711935:洋红 16777215:白色
acad.ActiveDocument.Application.preferences.Display.GraphicsWinModelBackgrndColor = 0

#设置文件自动保存间隔时间（分钟）
acad.ActiveDocument.Application.preferences.OpenSave.AutoSaveInterval = 2
```

## 图层操作

```
# 添加新图层，图层名称为"LAY"。
LayerObj = acad.ActiveDocument.Layers.Add("LAY")
acad.ActiveDocument.ActiveLayer = LayerObj
# 图层线型设置
try:
    acad.ActiveDocument.Linetypes.Load("ACAD_ISO08W100", "acadiso.lin")
except Exception as e:
    print(e,flush=True)
LayerObj.Linetype = "ACAD_ISO08W100"
```
